口コミのオフィシャル組み込み用カスタムページ
SunriseDigital/cs-sdx-web pull request #2
Opened 2017-04-07 00:51 UTC by shimizu-k-digi

### 概要
カラーピッカー用のコンポーネント作成

2017-04-13 04:04 UTC, gomo requested changes

2017-04-13 04:04 UTC, gomo commented on _private/js/modules/react/components/ColorPicker.js
> +      }
色が変わるたびに、イベントが初期化されるのが微妙ですね。複数はつかないのかな？その辺も心配です。

これ、



```jsx
  render() {
    return (
      <div className="color-picker">
        <input type="text" id={this.props.id} value={this.props.color} />
      </div>
    );
  }
```

じゃダメだった？それがいけたらcomponentWillReceivePropsは削除しちゃってOKですよね。

ダメだったら
```jsx
componentWillReceiveProps(){
  if(this.props.color != nextProps.color){
    this.$colorPicker.spectrum("option", "color", nextProps.color);
  }
}
```

とするのがいいかな。

😇

2017-04-13 04:04 UTC, gomo commented on _private/js/modules/react/components/ColorPicker.js
> +    $(".color-picker").find("#" + props.id).spectrum({
これはrefを使うのが一般的ですね。refというattrを使うと特定のエレメントを参照可能です。あとjQueryオブジェクトをはもしcomponentWillReceivePropsを使うならキャッシュしたほうがいです。componentDidMountで一回しか使わないなら、キャッシュはいらないけど。

```jsx
  componentDidMount(){
    this.$colorPicker = $(this.refs.colorPicker);
    this.$colorPicker.spectrum({
      color: this.props.color,
      change: function(color){ 
        this.props.onChangeColor(color.toHexString())
      }
    });
  }

  render() {
    return (
      <div className="color-picker">
        <input ref="colorPicker" type="text" id={this.props.id} />
      </div>
    );
  }
```

こうすればidの概念も削除できるかな。IDはかぶると危険なのでできれば使いたくないですね。

😇

2017-04-17 05:43 UTC, shimizu-k-digi commented on _private/js/modules/react/components/ColorPicker.js
> +      }
``` es6
  render() {
    return (
      <div className="color-picker">
        <input type="text" id={this.props.id} value={this.props.color} />
      </div>
    );
  }
```
で問題ありませんでした。。。

最初に試した時、value={this.props.color}の値が変わらなかったので`componentWillReceiveProps`を使ったのですが、上記でいけたのでいらなかったです。

2017-04-18 06:25 UTC, shimizu-k-digi commented on _private/js/modules/react/components/ColorPicker.js
> +      }
色を変更するのはsetメソッドでした。

colorは初期値の設定用でした。
https://bgrins.github.io/spectrum/#options-color

2017-04-19 03:36 UTC, gomo requested changes

2017-04-19 03:36 UTC, gomo commented on _private/js/modules/react/components/ColorPicker.js
> +      change: function (color) {
あ、これは下記で行けないだろうか？
```js
componentDidMount() {
    this.$colorPicker = $(this.refs.colorPicker);

    this.$colorPicker.spectrum({
      color: self.props.color,
      change: color => {
        this.props.onChangeColor(color.toHexString())
      }
    });
  }
```

es6の`() => {}`を使うとthisが外側と同じなったと思うけど、だめだった？まあ、これでもいいけど、sdxだし、ついでもあるので直してもらおうかな？

😇

2017-04-20 09:18 UTC, shimizu-k-digi commented on _private/js/modules/react/components/ColorPicker.js
> +      change: function (color) {
いけました！

> es6の() => {}を使うとthisが外側と同じなった

こちら覚えておきます！

2017-04-21 02:06 UTC, gomo approved these changes
👍

2017-05-09 04:04 UTC, merged