出勤情報・今すぐ遊べる子の改修 / 「接客中」フラグを設ける
SunriseDigital/cs-sdx-web pull request #5
Opened 2017-04-27 06:36 UTC by tkabeee

## Pivotal

https://www.pivotaltracker.com/story/show/135208459

## 親PR

https://github.com/SunriseDigital/nukinavi_unified/pull/250

2017-05-02 04:31 UTC, gomo requested changes

2017-05-02 04:31 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +      this.props.onPressEnterKey(data);
`this.state.keepInputIme`の時は呼ばない方向で問題ないのではないだろうか？

IMEの決定を検出したいなら、別のイベントを`onFixImeImput`とかをpropsで渡すようにしたらどうだろうか？

```js
  onKeyUp(e){
    if (this.state.keyCode.down.includes(e.keyCode) && e.keyCode == 13) {
      if (this.state.keepInputIme) {
        this.props.onFixImeImput(e);
      } else {
        this.props.onPressEnterKey(e);
      }
    }
    ...
  }
```

😇

2017-05-02 04:31 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +      },
keyCodeってstateで持つ必要あります？setStateを呼ぶとrenderが呼ばれDOMのチェックが走るので、必要なければメンバー変数などで問題ないと思いました。多分render内でstate. keyCodeを使ってないので必要ないですよね？

stateというと「このcomponent状態」という感じがしますが、実際のところ、「DOMに影響する状態」と解釈するのがいいんですかね？


😇

2017-05-02 04:31 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +      keepInputIme: false
こちらのkeepInputImeもメンバー変数で問題なさそうですかね？

😇

2017-05-02 04:31 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +      let data = this.state.keyCode;
KeyCodeを返しちゃうとShiftとかMetaキーが取れないのでeventをそのまま渡したほうがいいかな。

😇

2017-05-02 04:31 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +        down: (this.state.keyCode.down) ? this.state.keyCode.down.concat(e.keyCode) : [e.keyCode]
近藤くんおやすみでいなかったので確認できなかったのですが、このコード(downが何のために必要か？)が何の目的でやってるのか不明だったので解説してください。

😇

2017-05-10 05:56 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +      keepInputIme: false
react の State で管理するほどのものではありませんでした
余計な更新をさせてしまってましたのでメンバー変数に変更したいと思います

2017-05-10 06:01 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +        down: (this.state.keyCode.down) ? this.state.keyCode.down.concat(e.keyCode) : [e.keyCode]
「down」ですが、エンターキーを押したタイミングで、ShiftやCtrlキーが押された状態であるかどうかを判別する為、配列で持たせるようにしておりました

以降のコメントで event を返した方がよいというアドバイスを確認しましたが
event がShiftやCtrlキーを押している情報を持っているということなのですね
勉強不足でした。。eventを返すだけで済むなら、このdownは必要なさそうです

2017-05-10 06:03 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +      },
おっしゃる通りです。
keepInputImeのケースと同様に、こちらもメンバー変数で対応します

2017-05-10 07:17 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +      let data = this.state.keyCode;
eventを返すように対応しました

2017-05-10 07:19 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +      this.props.onPressEnterKey(data);
今回は、IME入力中はonPressEnterKeyメソッドを呼ばないように対応しました
IME決定の検出は必要が出た時の実装にまわしたいと思います

2017-05-10 07:23 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +      },
keycodeは、もつ必要がなくなりましたので削除対応にしました

2017-05-11 07:33 UTC, gomo requested changes

2017-05-11 07:33 UTC, gomo commented on _private/js/modules/react/components/TextEditor.js
> +    if (e.which == 13 && e.keyCode == 13) {
口頭で相談して、色々調査した件ですけど、keypressじゃなければ必要なさそうですかね？

😇

2017-05-12 03:38 UTC, tkabeee commented
## メモ

reactライブラリでkeyチェックしてる
https://github.com/Hacker0x01/react-datepicker/blob/master/src/datepicker.jsx#L269-L322

2017-05-12 05:01 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +    if (!this.keepInputIme && e.key === "Enter") {
gomo さんが作成されたキーイベント確認用のデモでは、
IME入力中のEnterキーでのkeydown,keyupイベントは発生していなかったので
IME入力判定は必要ないと思っていたのですが
このコンポーネントで確認したところ、IME入力中でもkeydown,keyupイベントが発生しておりました！？

という理由から、keyupイベントで一応IME入力判定を行うようにしております

### デモ
https://jsfiddle.net/miyata/o7dkozsg/

2017-05-17 09:10 UTC, tkabeee commented on _private/js/modules/react/components/TextEditor.js
> +    if (e.which == 13 && e.keyCode == 13) {
`e.which == 13`
こちらの条件は必要なさそうでしたが、
`!this.keepInputIme`
代わりにIME入力判定は必要でありました

こちらに理由をコメントしております
https://github.com/SunriseDigital/sdxweb/pull/5#discussion_r116153321

2017-05-18 02:30 UTC, gomo commented
👍

2017-05-18 02:31 UTC, gomo approved these changes
👍

2017-07-18 04:25 UTC, merged