画像アップロードボタンの見た目を自由に変えられるようにする
SunriseDigital/cs-sdx-web pull request #6
Opened 2017-05-12 08:40 UTC by tomita-ychr

## 概要
以下を可能にするためのPRです。
- `<input type=file>` の「選択されていません」 という表示を消したい
- input ボタンを自由に変えたい

## 使い方
Image のコンポーネント生成時に子props を渡すと、それが input の代わりに表示されるようになります。
```js
<ImageComponent>
  <button type="button">OriginalButtonSample</button>
</ImageComponent>
```

2017-05-15 08:14 UTC, gomo requested changes

2017-05-15 08:14 UTC, gomo commented on _private/js/modules/react/components/form/Image.js
> +    ReactDOM.findDOMNode(this.refs.fileInput).click();
これは多分

```js
this.refs.fileInput.click()
```

でOKじゃなかろうか？

https://facebook.github.io/react/docs/react-dom.html#finddomnode
ここを見ると、引数はcomponentになってるので、

例えば

```js
<Image ref="image" ... />
```

とかなってたら`ReactDOM.findDOMNode(this.refs.image)`で`<div className="wrapper">`が取れたようなイメージがあるんだけど・・・しかもドキュメントにもあるけど、中にrefをつけるのが一般的な気もする。

> In most cases, you can attach a ref to the DOM node and avoid using findDOMNode at all.

> ほとんどの場合、DOMノードにrefを付けることができ、findDOMNodeの使用をまったく避けることができます。

確認お願いします。

😇

2017-05-15 08:28 UTC, gomo requested changes
https://github.com/SunriseDigital/sdxweb/pull/6#pullrequestreview-38051994

これもですね。
二つに別れちゃったけど、お願いします。

2017-05-15 08:28 UTC, gomo commented on _private/js/modules/react/components/form/Image.js
> +              <div className="upload-trigger-wrapper" onClick={() => this.onClickOriginalButton()}>
これってonCLickのイベントを付与してるので、ほぼ100%cursolを指にしそうなので、styleに直接書いちゃいましょうか？もし、OFFにしたいシチュエーションがでてきたら、propsで何か渡せるようにすればいいし。今回は直に書いちゃって、propsによる分岐はいらないです。

😇

2017-05-15 08:28 UTC, gomo commented on _private/js/modules/react/components/form/Image.js
> +                {this.props.children}
ちなみにbuttonをおきたい時、typeを変えろという話があったけど下記でもいけますね。

```js
<input type="submit" onCLick={e => e.preventDefault()}>
```

これなら、submitボタンも使えます。・・・まあ、使いたいこともないだろうけど、参考までに。

2017-05-15 10:16 UTC, tomita-ychr commented on _private/js/modules/react/components/form/Image.js
> +              <div className="upload-trigger-wrapper" onClick={() => this.onClickOriginalButton()}>
作業してみたところ cursor が効いていなかったので確認してみました。
どうもタグによって親要素に書いた cursor がきかないケースがあるようです。
https://jsfiddle.net/TOMMY_aka_JPS/0vLyby8r/

div の代わりに ul を使ってみたり、li に style を定義してみましたが結果は同じでした。
現在わかっているだけで input と button タグは親要素に書いた cursor が効かないようです。
Chrome と Firefox で試してみましたがどちらも同じ結果でした。

input や button 自身に cursor を定義すればもちろん問題ありません。
ここには特に style は書かないようにして、HTMLコーダー作業時にCSSでなんとかしてもらう他ないかもしれません。

2017-05-15 10:28 UTC, tomita-ychr commented on _private/js/modules/react/components/form/Image.js
> +                {this.props.children}
あ、なるほどたしかにこれなら `type="submit"` でもいけそうですね。
ありがとうございます、原理が何か別の用途で使えることがあるかもしれないので覚えておくようにしますー

2017-05-15 10:29 UTC, tomita-ychr commented on _private/js/modules/react/components/form/Image.js
> +    ReactDOM.findDOMNode(this.refs.fileInput).click();
`this.refs.fileInput.click()` で問題なく動作できましたのでこちらに修正してコミットしました。

2017-05-16 02:40 UTC, gomo approved these changes
👍 

修正内容は問題ないです。
口頭で話しましたけど、他の人向けに書いておきます。

何かできないことがあった時、できないからやらないではなく、なぜできないのか突き止めましょう。

とはいえ、仕事なので時間も大事です。ちょっと調べてわからなかったら相談してください。

今回の件は、「ブラウザのデフォルトスタイルがbutton要素にcursor: defaultで付いていて、CSSの優先順位の問題で親につけたスタイルが効かない」というのが原因です。

メジャーなブラウザがボタンのカーソルをデフォルトに設定しているので、今回のケースでは変えない方が望ましいということになります。

2017-05-16 03:00 UTC, merged